# Generated by Django 4.2.7 on 2026-03-02 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_client_clientworkitem_and_more'),
        ('tickets', '0006_ticketbacklogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='users.client'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['technician', 'manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
