# Generated by Django 6.0.2 on 2026-02-21 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('callogs', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['technician', 'manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calllog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calllog',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='tickets.supportticket'),
        ),
        migrations.AddField(
            model_name='calllogactivity',
            name='call_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='callogs.calllog'),
        ),
        migrations.AddField(
            model_name='calllogactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineercomment',
            name='call_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_comments', to='callogs.calllog'),
        ),
        migrations.AddField(
            model_name='engineercomment',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['status'], name='callogs_cal_status_79734b_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['assigned_technician', 'status'], name='callogs_cal_assigne_f077b6_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['created_at'], name='callogs_cal_created_f125e8_idx'),
        ),
    ]
