# Generated by Django 4.2.7 on 2026-03-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callogs', '0010_jobbacklogentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobbacklogentry',
            new_name='callogs_job_is_wait_b961e7_idx',
            old_name='callogs_job_is_waiti_8dfdb6_idx',
        ),
    ]
