# Generated by Django 4.2.7 on 2026-03-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientprofile',
            new_name='users_clien_registr_334521_idx',
            old_name='users_clien_registr_767ff7_idx',
        ),
        migrations.RenameIndex(
            model_name='clientprofile',
            new_name='users_clien_created_eed98c_idx',
            old_name='users_clien_created_d5dc4d_idx',
        ),
    ]
