# Generated by Django 4.2.7 on 2026-03-02 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callogs', '0007_update_currency_to_zwg'),
        ('tickets', '0006_ticketbacklogentry'),
        ('users', '0006_rename_users_clien_registr_767ff7_idx_users_clien_registr_334521_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('ticket', 'Ticket'), ('job', 'Job Card')], max_length=10)),
                ('reference_number', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['technician', 'manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_work_items', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='users.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_work_items', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_work_item', to='callogs.calllog')),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['technician', 'manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_client_work_items', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_work_item', to='tickets.supportticket')),
            ],
            options={
                'db_table': 'client_work_items',
                'ordering': ['-source_created_at', '-created_at'],
                'indexes': [models.Index(fields=['item_type', 'status'], name='client_work_item_ty_f04e5b_idx'), models.Index(fields=['reference_number'], name='client_work_referen_1bbf5e_idx'), models.Index(fields=['source_created_at'], name='client_work_source__b277d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_email_4c8bec_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='clients_created_4c189f_idx'),
        ),
    ]
