# Generated by Django 4.2.7 on 2026-03-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='users_leave_status_769c41_idx',
            old_name='users_leave_status_25f5cb_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='users_leave_request_d6324c_idx',
            old_name='users_leave_request_08b321_idx',
        ),
    ]
